### ISSUE TITLE
Markdownify Appimage 

### ISSUE THREAD

**Issue by kskarthik** [amitmerchant1990/electron-markdownify#1]
I made latest 64bit [appimage](http://appimage.org) for markdownify which can run on any linux distro by just by giving permissions _chmod+x_ & double clicking on it. 

Download: https://www.dropbox.com/s/r6sekuq2496k2r7/Markdownify-x64?dl=0

Hope you like it :smiley:

**Comment by amitmerchant1990** [comment]
Great! I'll try it out. Thanks! :blush:
