### ISSUE TITLE
Steals Ctrl + Shift + T combo on Windows

### ISSUE THREAD

**Issue by patricknelson** [amitmerchant1990/electron-markdownify#14]
Steps recorded in screen capture (below):
1. Open Chrome
2. Open `electron-markdownify`
3. Switch back to Chrome and close a few tabs via `ctrl + w`
4. While **still** in chrome: Press `ctrl + shift + t` to reopen last closed tab, but instead `electron-markdownify` has somehow kidnapped this combination globally.

![2016-10-28_10-53-48](https://cloud.githubusercontent.com/assets/4269377/19816599/e01d6250-9cfc-11e6-9730-e6ca80b432b2.gif)

**Comment by amitmerchant1990** [comment]
Hi @patricknelson Yes. I'm aware aware about issue and it's being occurring due to `globalShortcut` module of Electron. So, until the solution of the same doesn't come out, we need to try another way out. I'll work on it and try to fix it soon.

**Comment by patricknelson** [comment]
I see. I just looked into this a bit, cloned and rebuilt this repo and looked the code a little deeper. They're never going to fix that I think because it would go against the _purpose_ of the module, as it's always going to be [OS-level shortcuts](https://github.com/electron/electron/blob/master/docs/api/global-shortcut.md). So, as long as you're calling `globalShortcut.register('CmdOrCtrl+Shift+t', ...)` then people use these shortcuts OUTSIDE of the app are going to drop this app instantly because of the conflict in the separation of concerns.

I'd suggest finding a way to listen to all of these events on the `document` element or adding them as menu entries. It just might be a little more difficult since you won't be able to use the nice cross-OS compatible syntax (e.g. `CmdOrCtrl+Shift+t`) but I'm sure it's still doable. For now this sort of kills the app for me, unfortunately.

**Comment by patricknelson** [comment]
p.s. Here's a related discussion that I found which covers this topic on the module itself https://github.com/electron/electron/issues/1334

Based on what I'm seeing at the bottom I'll submit a quick PR for you to test out an alternative!

**Comment by amitmerchant1990** [comment]
#15 this. Closing the issue.
