### ISSUE TITLE
Code syntax highlighting (feature request)

### ISSUE THREAD

**Issue by patricknelson** [amitmerchant1990/electron-markdownify#16]
Partially logging for my own reference (since I could implement this) but also in case anyone else gets to it before I do. Would love to have [Github flavored syntax highlighting](https://help.github.com/articles/creating-and-highlighting-code-blocks/) for code blocks

For example, this raw markdown block:

    ```js
    setTimeout(function() {
        alert('hello!');
    }, 1000);
    ```

Currently looks like this when rendered:

```
setTimeout(function() {
    alert('hello!');
}, 1000);
```

Goal would be to have language specific highlighting when a language identifier is included:

```js
setTimeout(function() {
    alert('hello!');
}, 1000);
```

Based on some superficial research, implementation would need to somehow utilize the `highlight` callback in `marked` (here) and incorporation of highlight.js.

- https://github.com/chjj/marked#highlight
- https://highlightjs.org/usage/

**Comment by amitmerchant1990** [comment]
As suggested above, https://github.com/amitmerchant1990/electron-markdownify/commit/4db81648f483fbdfb592951caadae0e69b3b34a3 have solved the issue.

**Comment by patricknelson** [comment]
Looks great, thanks!
