### ISSUE TITLE
BUG Bottom scroll bar scrolls out of view.

### ISSUE THREAD

**Issue by patricknelson** [amitmerchant1990/electron-markdownify#18]
In the midst of developing PR #17 I realized the bottom scrollbar is only visible when scrolled all the way to the bottom. Not sure why. FYI, this is a capture from the `master` branch (not affected by any of my changes).

![2017-01-20_14-19-11](https://cloud.githubusercontent.com/assets/4269377/22167489/9ab6e1c6-df1b-11e6-922b-316cc018409e.gif)

**Comment by amitmerchant1990** [comment]
Hi @patricknelson I've checked this particular issue and found that the bottom scroll is appearing because of the image that is being stretched out. I'll need to fix the responsiveness of the images when showing them in the preview section. Thanks for pointing it out!

**Comment by amitmerchant1990** [comment]
Resolved the issue in this https://github.com/amitmerchant1990/electron-markdownify/commit/ef54685c789c1ccdd5fa8d821f29d1a7b82358a3 commit.
