### ISSUE TITLE
Fix browser support badges from Sauce Labs on FAST-DNA README.md

### ISSUE THREAD

**Issue by Falkicon** [amitmerchant1990/electron-markdownify#33]
The Sauce Labs badges under Browser support are not updating:

![image](https://user-images.githubusercontent.com/943328/50381072-fda31b80-0631-11e9-994b-7819e91c2e66.png)

**Comment by Falkicon** [comment]
Oops, wrong project...

**Comment by amitmerchant1990** [comment]
Which project did you intent to open up this issue?
