### ISSUE TITLE
format function should't use string.split.join to replace all 

### ISSUE THREAD

**Issue by banyudu** [amitmerchant1990/electron-markdownify#5]
For example:
Document: `hello\_world`
Italic button will format it to `_hello\world_`, the underscore between _hello_ and _world_ missed after format.

**Comment by amitmerchant1990** [comment]
Solved in here https://github.com/amitmerchant1990/electron-markdownify/commit/6a529ced9d986f0f70af59187a7bbb1c03d9e700. Thanks @banyudu.
